.include <src.opts.mk>

.include "../../Makefile.inc"

.include "../../Makefile.crypto"

LIB=	wpatls
INTERNALLIB=

.PATH:	${WPA_DISTDIR}/src/tls

# We are only interested in includes at this point. Not libraries.
LIBADD=

.include <bsd.lib.mk>
