#!/bin/sh -e

WORKDIR=/data/1/adrian/freebsd/freebsd-router/
REPODIR=/data/1/freebsd/router/pkgs/

mkdir -p ${REPODIR}
env MAKEOBJDIRPREFIX=${WORKDIR}/freebsd-obj \
    REPODIR=${REPODIR} \
    KERNCONF=ROUTER \
    make -s -j12 packages
