#!/bin/sh -e

WORKDIR=/data/1/adrian/freebsd/freebsd-router/
REPODIR=/data/1/freebsd/router/pkgs/

# Note: the first kernel is the default /boot/kernel/ files;
# the rest of them get named /boot/kernel.<NAME> .
# So before adding say, GENERIC to the front, first all of my
# devices need updating to include GENERIC so I don't break them.

X_KERNEL_LIST="GENERIC GENERIC-NODEBUG ROUTER ROUTER_DEBUG ROUTER_RSS"

env MAKEOBJDIRPREFIX=${WORKDIR}/freebsd-obj \
    make -s -j12 buildworld buildkernel KERNCONF="${X_KERNEL_LIST}"

